import type { Metadata } from "next";
import "bootstrap/dist/css/bootstrap.min.css"
import { Inter } from "next/font/google";
import "./globals.css";
import AddBootstrap from "./AddBootstrap";
import Navbar  from "./components/Navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Ad Banner App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AddBootstrap/>
        <Navbar/>
        {children}
      </body>
    </html>
  );
}
